# Generated by Django 3.0.6 on 2020-05-14 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_auto_20200514_0038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products_model',
            name='image',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
