# Generated by Django 3.0.6 on 2020-05-14 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_auto_20200514_0042'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Backend_model',
        ),
    ]
