# Generated by Django 3.0.6 on 2020-05-14 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_delete_backend_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transactions_model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_array', models.CharField(max_length=100, unique=True)),
                ('total', models.IntegerField()),
                ('tax', models.CharField(max_length=100, unique=True)),
                ('employee', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
