# Generated by Django 3.0.6 on 2020-05-19 23:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_cart_model'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transactions_model',
            old_name='product_array',
            new_name='products',
        ),
        migrations.RemoveField(
            model_name='transactions_model',
            name='employee',
        ),
    ]
