# Generated by Django 3.0.6 on 2020-05-20 00:07

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_auto_20200519_1652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions_model',
            name='products',
            field=jsonfield.fields.JSONField(),
        ),
    ]
