# Generated by Django 3.0.6 on 2020-05-20 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0010_auto_20200519_1707'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions_model',
            name='products',
            field=models.CharField(max_length=1000),
        ),
    ]
